### PR TITLE
Possibility to turn off ssl certificate validation and proxy connection

### PR DESCRIPTION
**Pull request by tosher**
* Possibility to turn off ssl certificate validation (for self-signed certs on corp. wikies)
* Proxy connection support.

### CODE REVIEW

**Comment by danmichaelo** [comment]
Sorry for the delay on this! The argument name `do_ssl_cert_verify` is quite long. What do you think about renaming it to just `verify` to follow requests? Another idea would be to just pass `**kwargs` to requests.

**Comment by scholer** [comment]
I'd be very happy if **kwargs is passed on to requests. 
In my research lab we are maintaining a custom version of @tosher 's Mediawiker plugin for Sublime, which again has a custom (old) version of mwclient, all so that we can inject custom headers (with a stored SessionID data) before making the initial connection. Yes, there are other ways to do this, using do_init=False, and then updating headers/etc after init, but this would just require more customizations to Mediawiker instead. If we can simply configure the requests Session with kwargs on init, that would make life easier. And thanks again, Dan, for making this library! :)

**Comment by tosher** [comment]
It will be requests specified kwargs?
```python
class Site(object):
    def __init__(self, ..... **kwargs):
        self.kwargs = kwargs
        # ...
    # in raw_call
        stream = self.connection.post(fullurl, data=data, files=files, headers=headers, **self.kwargs)
```

**Comment by danmichaelo** [comment]
:+1: @tosher . But please name it something like `self.connection_kwargs = kwargs`.

**Comment by tosher** [comment]
done

**Comment by eighthave** [comment]
This kind of change should really be accompanied by tests.  This is messing with the core security of this library, and getting it wrong could mean the certificate verification gets disabled for people who need it.

**Comment by tosher** [comment]
* It's not default option for mwclient
* It's base functionality of requests lib

**Comment by tosher** [comment]
Maybe, variant like this will be better?
* http://python-redmine.readthedocs.org/configuration.html#connection-options
Special parameter for requests library, not global kwargs..

**Comment by danmichaelo** [comment]
> Maybe, variant like this will be better?
> * http://python-redmine.readthedocs.org/configuration.html#connection-options
>
> Special parameter for requests library, not global kwargs..

Agree, that's a better solution since we will never get a conflict with internal arguments. Would you mind updating the pull request? Then I can merge it right away. Sorry I forgot about this.

**Comment by tosher** [comment]
Ok, i will..

**Comment by tosher** [comment]
Travis is broken?

**Comment by danmichaelo** [comment]
> Travis is broken?

Related to one of the deps, we can ignore that.

Being a little picky, I'm not sure if we need to introduce kwargs here.. I'd suggest just adding `requests=None` as a param to the method, and then do:

    self.requests = requests or {}

(since adding `requests={}` as a param is [not a good idea](http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments))

Also, could you squash all the commits into one commit? Just do a `git push --force` afterwards

**Comment by tosher** [comment]
* 'Code quality decreased by -0.63%'
    - `Too many local variables`

:) No problem, i'll remove kwargs. 

> `all the commits into one commit`

ok

**Comment by waldyrious** [comment]
@danmichaelo for future reference, PRs can [now](https://github.com/blog/2141-squash-your-commits) be squashed at merge time by the maintainer, so there's no need for the awkward `push -f force` dance anymore :)

**Comment by danmichaelo** [comment]
> @danmichaelo for future reference, PRs can [now](https://github.com/blog/2141-squash-your-commits) be squashed at merge time by the maintainer, so there's no need for the awkward `push -f force` dance anymore :)

Oooh, that's useful

**Comment by tosher** [comment]
Done.
> no need for the awkward push -f force dance anymore :)

P.S. I'm skipped the dance :)

**Comment by danmichaelo** [comment]
Thanks, no dance needed :)

**Pull request merged**
