### PR TITLE
Update authentication method docs

### LINKED ISSUE #322: Update authentication documentation page
The info on authenticating in the docs doesn't cover `clientlogin()`, and - as suggested in https://github.com/mwclient/mwclient/issues/315 - could make it clearer that the options that allow HTTP authentication aren't alternatives for logging into mediawiki itself.

### PR DESCRIPTION
**Pull request by marcfrederick**
Attempt to resolve #322, by clarifying the authentication section of the documentation.

### CODE REVIEW

**Comment by AdamWill** [comment]
I kinda preferred how the existing file has OAuth *first*. We really want to encourage people to use OAuth for what's probably the most common use case (connecting to wikimedia wikis). In my experience you should always put the thing people are usually meant to do *first*, then other stuff comes afterwards.

**Comment by marcfrederick** [comment]
> In my experience you should always put the thing people are usually meant to do _first_, then other stuff comes afterwards.

Good point, I've switched the sections back to the original order.

**Comment by AdamWill** [comment]
Should we also document `clientlogin()`?

**Comment by AdamWill** [comment]
Well, this is clearly an improvement anyway, so let's go with it. I guess I'll write a follow-up to document `clientlogin`.

**Pull request merged**
