### PR TITLE
-

### PR DESCRIPTION
**Pull request by 1bakedpotato**
-

### CODE REVIEW

**Comment by waldyrious** [comment]
@1bakedpotato I hope you don't mind, but I'll restore the original title and description of this PR. Otherwise it would look quite puzzling in the issue tracker.

**Comment by waldyrious** [comment]
@danmichaelo is this something we should merge? I haven't touched this code in a while so I'm not sure.

**Comment by danmichaelo** [comment]
Yes, we should! Sorry I've been not very responsive here. Since the fork was deleted, I wasn't able to fetch the commit from @ghost anymore, but I will give credit in the changelog!

**Comment by waldyrious** [comment]
@danmichaelo actually it is still possible to check out the pull request; GitHub keeps a copy of the branch stored in the target repository, which you can checkout locally via `git fetch origin pull/PR_NUMBER/head:BRANCH_NAME`; in this case, that would be:

    git fetch origin pull/249/head:edit-section-zero

That's explained in [this GitHub help article](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally). Hope that helps for next time :)

**Comment by danmichaelo** [comment]
Hah, thanks, that's nice to know :)  At least, I added credits to bakedpotato1 to https://github.com/mwclient/mwclient/releases/tag/v0.10.1

**Pull request closed without merging**
