### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by waldyrious**
- Update copyright notice to reflect changes in recent years
- Add title to make the license file more human-friendly

### CODE REVIEW

**Comment by danmichaelo** [comment]
Thanks! What do you think about removing the year range altogether? Like here: https://github.com/facebook/react/blob/master/LICENSE

Or alternatively just use the date of first publication (2006) rather than a date range?

**Comment by waldyrious** [comment]
Both approaches are OK with me. There are [compelling arguments](https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/) to use a date range, but the no-date approach of React seems like a nice shortcut to signify "all time" (and avoid the need to constantly update the year range).

If after reading the page linked above you still think that using no date is reasonable, I'll make the change.

**Comment by danmichaelo** [comment]
Thanks, that's a well-written post, but I'm a bit confused about the arguments, it seems to boil down to precedence, doesn't it?

Sticking to precedence or standards can be a reason by itself though. But having a date range that becomes outdated every year (unless the project development actually stops, that is) still seems a bit clumsy to me when the whole copyright statement doesn't really carry any legal function anymore. 

It still seems reasonable to me to remove the date range, but I'm also OK with keeping it. At least if you could help me update it at least every third year or so 😄

**Comment by waldyrious** [comment]
IMO if the project changed licenses (or license holders), a date range would be relevant. As it stands, it doesn't really matter that much to have the boundaries there, since no project with the same name or content (and different licensing conditions) exists outside them anyway. Let's go with the easier solution then ;)

**Comment by danmichaelo** [comment]
> IMO if the project changed licenses (or license holders), a date range would be relevant

That's true!

**Pull request merged**
