### PR TITLE
0.11.0 release prep

### PR DESCRIPTION
**Pull request by AdamWill**
This has the commit for the 0.11.0 release, plus a preparatory tweak to pyproduct.md. After merging this I need to figure out how to get the tag pushed, then the release should happen.

### CODE REVIEW

**Comment by AdamWill** [comment]
@mwclient/maintainers ok, this is waiting for another maintainer to approve the action (I set it up that way as it's The Right Thing To Do). If someone else can review/approve that'd be awesome. Otherwise I'll use superpowers to do it tomorrow. Thanks!

**Comment by marcfrederick** [comment]
I've approved the action run and the new version has been successfully published 🚀 Thank you @AdamWill for all the work you've put into this.

**Comment by AdamWill** [comment]
woohoo! thanks for the approval and cleaning up the tickets. so happy we got this done :)

**Comment by RheingoldRiver** [comment]
I'm gonna write up a small announcement on my blog that mwclient 0.11 is live and people should update, anything particular you want me to include other than a changelog? I can include a paragraph or two directly quoting you if you want

**Comment by AdamWill** [comment]
Great idea! Nothing in particular, except I think it'd be nice to credit Dan, Waldy and Bryan if you weren't already planning to do so. I threw something up on Mastodon earlier - https://fosstodon.org/@adamw/112950435865982501 (acknowledgments are in the reply as I ran out of space). I hope that *is* your Mastodon! :)

**Comment by AdamWill** [comment]
I guess also maybe hedge "should upgrade" a *little* bit as the release has a loooooot of change and it's possible there might be some unexpected consequence, so I'd probably make the message "test it out, upgrade if it's good, let us know if not"?

**Comment by RheingoldRiver** [comment]
sounds good! ill send the link here when it's live

**Comment by AdamWill** [comment]
Awesome post! Thanks!

**Pull request merged**
