### PR TITLE
remove: py34 references

### PR DESCRIPTION
**Pull request by marcfrederick**
Support for Python 3.4 is stated in multiple places and already tested by the tox.ini

### CODE REVIEW

**Comment by waldyrious** [comment]
This had been added before, in 22ac6ecb8. It was later removed in 737e7cc26.

Can you point to the places where support for Python 3.4 is claimed? We probably should remove them.

**Comment by marcfrederick** [comment]
@waldyrious I've updated this pull request to remove the references to Python 3.4 instead.

**Comment by waldyrious** [comment]
Thanks, @marcfrederick! Can you just fix the commit message? It currently says "remove: py37 references" but it should be "remove: py34 references" instead.

**Comment by marcfrederick** [comment]
Done @waldyrious

**Pull request merged**
