### PR TITLE
Rename constructor arg requests to reqs to Fix #118

### LINKED ISSUE #118: NoneType has no Session()
The merge of #105 seems to have broken unit tests (and the client ^_^)

```
>           self.connection = requests.Session()
E           AttributeError: 'NoneType' object has no attribute 'Session'

../official_mwclient/mwclient/mwclient/client.py:91: AttributeError
============================================================================ 20 failed, 21 passed in 1.24 seconds ============================================================================
```

I tried with the python interprer, I have the same results:
```
>>> import mwclient
>>> mwclient.__ver__
'0.8.2.dev1'
>>> mwclient.Site('commons.wikimedia.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mwclient/client.py", line 91, in __init__
    self.connection = requests.Session()
AttributeError: 'NoneType' object has no attribute 'Session'
```

I'd say masking the requests package with an argument name is not a good idea ^_^

### PR DESCRIPTION
**Pull request by PierreSelim**
Beaware argument requests from the constructor has been rename reqs

### CODE REVIEW

**Comment by danmichaelo** [comment]
Thanks :) Strangely the Travis build still fails, gotta figure out why..

**Comment by scholer** [comment]
Hi,
Sorry to be commenting on such an old PR. But I just found myself looking for the "requests kwargs" parameter to send to ```Site.__init__```, and I completely missed that it was called ```reqs```. It's been a while since I last had to initialize a ```mwclient.Site``` directly, so it might just be me. But, it made me think whether it would make sense to rename the parameter to something slightly more verbose, e.g. ```requests_args```? Or alternatively document the ```reqs``` parameter it in the docstring of ```Site```?

There haven't been any official mwclient release since this PR, so I figure it's still OK to change parameter names if we want.

**Comment by danmichaelo** [comment]
No prob, I actually agree when I look at it now. `reqs` isn't very intuitive, and it means autocompletion doesn't help you if you type something like `requ`.. so I'm open for changing it. Is `requests_args` what we settle for?

**Comment by danmichaelo** [comment]
Ping @tosher as the original author of #105

**Comment by tosher** [comment]
I'm agree with any variant :) 
.. in Mediawiker's version on client i'm using `kwargs` instead of sep. parameter :)

**Pull request merged**
