### PR TITLE
Fix Client.ask getting no results from semantic query,  Issue#161

### PR DESCRIPTION
**Pull request by ubibene**
Check : 

```
import mwclient
import six

site=mwclient.Site(('https','sandbox.semantic-mediawiki.org'),'/w/')
query_with_results="[[Has email::+]]|?Label" 
query_with_no_results="[[Has email::xxxx]]|?Label" 

answer=site.ask(query_with_results)
empty_answer=site.ask(query_with_no_results)

print("non empty answer")
for a in answer:
    for k,v in six.iteritems(a):
        print(k)
        print(v)
print("-----------")
print("empty answer")
for a in empty_answer:
    for k,v in six.iteritems(a):
        print(k)
        print(v)
print("-----------")
```

Output:
```
non empty answer
Issue/2093/1# 429eac66925d6bdd9dfecad0fc7e7ce7
{u'fulltext': u'Issue/2093/1# 429eac66925d6bdd9dfecad0fc7e7ce7', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Issue/2093/1#_429eac66925d6bdd9dfecad0fc7e7ce7'}
Lorem ipsum Export
{u'fulltext': u'Lorem ipsum Export', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum_Export'}
Issue/2093/1
{u'fulltext': u'Issue/2093/1', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Issue/2093/1'}
Issue/1855 (Lorem ipsum)
{u'fulltext': u'Issue/1855 (Lorem ipsum)', u'displaytitle': u'Lorem ipsum', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Issue/1855_(Lorem_ipsum)'}
Lorem ipsum# 0a872dd5b2e992230eac6aa27ffc0174
{u'fulltext': u'Lorem ipsum# 0a872dd5b2e992230eac6aa27ffc0174', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum#_0a872dd5b2e992230eac6aa27ffc0174'}
Azure
{u'fulltext': u'Azure', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': [{u'displaytitle': u'', u'fulltext': u'Azure', u'namespace': 0, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Azure', u'exists': u'1'}]}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Azure'}
Lorem ipsum
{u'fulltext': u'Lorem ipsum', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum'}
-----------
empty answer
-----------
```

More over I replaced x.itermitems() by six.iteritems(x) for Python 2.7/3.x compatibilty

### CODE REVIEW

**Comment by ubibene** [comment]
I added a check in case of the query is malformed : in that case Semantic Mediawiki is returning an error message with a structure different from a message indicating no results

To check 

```
import mwclient
import six

site=mwclient.Site(('https','sandbox.semantic-mediawiki.org'),'/w/')
query_with_results="[[Has email::+]]|?Label" 
query_with_no_results="[[Has email::xxxx]]|?Label" 
malformed_query="[[Has em"

answer=site.ask(query_with_results)
empty_answer=site.ask(query_with_no_results)
error_answer=site.ask(malformed_query)

print("-----------")
print("non empty answer")
for a in answer:
    for k,v in six.iteritems(a):
        print(k)
        print(v)

print("-----------")
print("empty answer")
for a in empty_answer:
    for k,v in six.iteritems(a):
        print(k)
        print(v)

print("-----------")
print("maformed query")
for a in error_answer:
    for k,v in six.iteritems(a):
        print(k)
        print(v)
print("-----------")


```
output is 
```
-----------
non empty answer
Issue/2093/1# 429eac66925d6bdd9dfecad0fc7e7ce7
{u'fulltext': u'Issue/2093/1# 429eac66925d6bdd9dfecad0fc7e7ce7', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Issue/2093/1#_429eac66925d6bdd9dfecad0fc7e7ce7'}
Lorem ipsum Export
{u'fulltext': u'Lorem ipsum Export', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum_Export'}
Issue/2093/1
{u'fulltext': u'Issue/2093/1', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Issue/2093/1'}
Issue/1855 (Lorem ipsum)
{u'fulltext': u'Issue/1855 (Lorem ipsum)', u'displaytitle': u'Lorem ipsum', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Issue/1855_(Lorem_ipsum)'}
Lorem ipsum# 0a872dd5b2e992230eac6aa27ffc0174
{u'fulltext': u'Lorem ipsum# 0a872dd5b2e992230eac6aa27ffc0174', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum#_0a872dd5b2e992230eac6aa27ffc0174'}
Azure
{u'fulltext': u'Azure', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': [{u'displaytitle': u'', u'fulltext': u'Azure', u'namespace': 0, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Azure', u'exists': u'1'}]}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Azure'}
Lorem ipsum
{u'fulltext': u'Lorem ipsum', u'displaytitle': u'', u'exists': u'1', u'namespace': 0, u'printouts': {u'Label': []}, u'fullurl': u'https://sandbox.semantic-mediawiki.org/wiki/Lorem_ipsum'}
-----------
empty answer
-----------
maformed query
-----------

```

**Comment by danmichaelo** [comment]
This is great! But you introduced a merge commit in a6980e. Could you try to do `git rebase origin master`, fix the conflict, `git rebase --continue`, then `git push -f`

**Comment by ubibene** [comment]
Hi,
I'm a total git newbie, so I'm not suprised I screw up in the process ;-)

I'll try what you said (which I don't understand at the moment). I'll try this tonight when at home.

 If I cannot figure it out,  may be you could change the 10 lines in mwlcient.site.ask() ?

**Comment by danmichaelo** [comment]
No prob, I can always fix it if you get stuck, I realize this is not super easy if you're not used to fix conflicts! In any case, the cause was that you didn't pull in `origin/master` before starting to work on this. After you've pulled, it's also always a good idea to checkout a new branch when you start working on something that is going to be a PR instead of working directly on master.

P.s. `git log --graph --oneline` is useful to visualize what happened.

**Comment by ubibene** [comment]
@danmichaelo 
> git rebase origin/master
did nothing at all

So I tried to check out using the commit just bebore  a6980e and then introduced the fix for issue #161 , commited, and pushed.

If that's not ok, could you please integrate the fix yourself ? ( It's about the code in client.ask() only)

Thanks

**Comment by danmichaelo** [comment]
Ah, sorry, origin is of course referring to *your* repo. Here's the recipe for getting the conflict :)

    git remote add upstream https://github.com/mwclient/mwclient.git
    git rebase upstream/master

**Comment by ubibene** [comment]
Ok, I tried to do it, may you have a look ? 

If the git stuff is screwed , you'd better fix client.ask() with the code below. I can then delete my mwclient fork and make a fresh fork.


```
def ask(self, query, title=None):
        """
        Ask a query against Semantic MediaWiki.

        API doc: https://semantic-mediawiki.org/wiki/Ask_API

        Returns:
            Generator for retrieving all search results.
            Iterating over the generator gives a dictionnary containing the answers
            to the query.
            The dictionnary is empty if either:
               - the query is valid but there are no answers,
               - or if the query is not valid.

        Examples:

            >>> query = "[[Category:my cat]]|[[Has name::a name]]|?Has property"
            >>> answer = site.ask(query)
            >>> for a in answer:
            >>>     for key,value in a.iteritems() # or a.items() in python 3.
            >>>         print(key)
            >>>         print(value)
        """
        kwargs = {} 
        if title is None:
            kwargs['title'] = title

        offset = 0
        while offset is not None:
            results = self.raw_api('ask', query='{query}|offset={offset}'.format(
                query=query, offset=offset), http_method='GET', **kwargs)
            if results.get('error'):  # malformed query, maybe should raise an exception
                offset = None 
                yield {}
            elif results.get('query'):
                answer = results.get('query').get('results')
                if (answer):
                    offset = results.get('query-continue-offset')
                    for key, value in six.iteritems(answer):
                        yield {key: value}
                else:  # query returns no results
                    offset = None 
                    yield {}

```

**Comment by ubibene** [comment]
OK , I'll close this PR and rework the git thing before reopening a new PR

**Pull request closed without merging**
